version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - /var/home/rackett/DjangoProjects/BlogContainer:/workspaces/ryans-blog/BlogContainer
    command: sleep infinity
    ports:
      - "8000:8000"
    # Remove network_mode, use depends_on instead
    depends_on:
      - db
    # Add a shared folder volume for file transfer
      
  db:
    image: postgres:latest
    restart: always
    # This line tells Podman to ignore internal user switching, 
    # which fixes most "Exit Code 1" errors on Fedora/Bluefin
    user: "0:0" 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql:Z

    

volumes:
  postgres-data:
